#!/bin/bash

red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
bl='\e[36;1m'
bd='\e[1m'

clear
echo ""
echo ""
echo -e " ╔═══════════════════════════════════════╗" | lolcat
echo -e " ║  MENU PANEL  AUTO  INSTALL  SCRIPT    ║" | lolcat
echo -e " ╠═══════════════════════════════════════╝" | lolcat
echo -e " $bd║\e[m"
echo -e " $bd║\e[m 1$bl]\e[m$bd AUTOSCRIPT SPECIAL TROJAN 443"
echo -e " $bd║\e[m"
echo -e " $bd║\e[m 2$bl]\e[m$bd AUTOSCRIPT PREMIUM V2"
echo -e " $bd║\e[m"
echo -e " $bd║\e[m 3$bl]\e[m$bd INSTALL AUTOSCRIPT WITH LICENSE"
echo -e " $bd║\e[m"
echo -e " $bd║\e[m 4$bl]\e[m$bd INSTALL AUTOSCRIPT WITH LICENSE TRIAL MODE"
echo -e " $bd║\e[m"
echo -e " $bd║\e[m x$bl]\e[m$bd BATAL INSTALL AUTOSCRIPT"
echo -e " $bd║\e[m"
echo -e " ╠═══════════════════════════════════════╗" | lolcat
echo -e " ║ COPYRIGHT ©2022 AUTOSCRIPT BY FSIDVPN ║" | lolcat
echo -e " ╚═══════════════════════════════════════╝" | lolcat
echo -e "\e[1;31m"
read -p "    Please select an option :  "  installscript
echo -e "\e[0m"
case $installscript in
    1)
    clear
    figlet -f slant "INSTALLING SCRIPT PLEASE WAIT" | lolcat
    rm -f setup.sh && apt update && apt upgrade -y && update-grub && sleep 2 && apt-get update -y && apt-get upgrade && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && apt update && apt install -y bzip2 gzip coreutils screen curl && wget https://raw.githubusercontent.com/fsidvpn/scriptvps/main/setup && chmod +x setup && screen -S setup ./setup
    exit
    ;;
    2)
    clear
    figlet -f slant "INSTALLING SCRIPT PLEASE WAIT" | lolcat
    rm -f setup.sh && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && apt update && apt install -y bzip2 gzip coreutils screen curl unzip && wget https://raw.githubusercontent.com/fsidvpn/vps/main/setup.sh && chmod +x setup.sh && sed -i -e 's/\r$//' setup.sh && screen -S setup ./setup.sh
    exit
    ;;
    3)
    clear
    figlet -f slant " INSTALLING WITH LICENSE" | lolcat
    rm -f License && wget https://autosc.me/PREM30 && clear && chmod +x PREM30 && ./PREM30
    ;;
    4)
    clear
    figlet -f slant " INSTALING AUTOSCRIPT " | lolcat
    rm -f trial && wget https://autosc.me/TRIAL3 && clear && chmod +x TRIAL3 && ./TRIAL3
    ;;
    x)
    figlet -f slant " FSIDVPN SCRIPT INSTALLER " | lolcat
    sudo -i
    exit
    echo -e "\e[1;31mPlease enter an correct number\e[0m"
    clear
    exit
    ;;
esac
