#!/bin/bash
# ****************************************
# Program: Autoscript Setup VPS 2021     *
# Developer: KingKongVPN                 *
# Nickname: xiihaiqal                    *
# Modify : @xiihaiqal                    *
# ****************************************
