#!/bin/bash

red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
bl='\e[36;1m'
bd=

apt install figlet -y
apt install lolcat -y
gem install lolcat

clear
echo ""
echo ""
echo -e " ╔═══════════════════════════════════════╗" | lolcat
echo -e " ║  MENU PANEL  AUTO  INSTALL  SCRIPT    ║" | lolcat
echo -e " ╠═══════════════════════════════════════╝" | lolcat
echo -e " $bd║\e["
echo -e " $bd║  \e[ 1]\e[ AUTOSCRIPT SPECIAL TROJAN 443" | lolcat
echo -e " $bd║\e["
echo -e " $bd║  \e[ 2]\e[ AUTOSCRIPT PREMIUM" | lolcat
echo -e " $bd║\e["
echo -e " $bd║  \e[ 3]\e[ INSTALL AUTOSCRIPT WITH LICENSE" | lolcat
echo -e " $bd║\e["
echo -e " $bd║  \e[ 4]\e[ INSTALL AUTOSCRIPT WITH TRIAL MODE" | lolcat
echo -e " $bd║\e["
echo -e " $bd║  \e[ X]\e[ BATAL INSTALL AUTOSCRIPT" | lolcat
echo -e " $bd║\e["
echo -e " ╠═══════════════════════════════════════╗" | lolcat
echo -e " ║ COPYRIGHT ©2022 AUTOSCRIPT BY FSIDVPN ║" | lolcat
echo -e " ╚═══════════════════════════════════════╝" | lolcat
echo -e "\e[1;31m"
read -p "    Please select an option :  "  installscript
echo -e "\e[0m"
case $installscript in
    1)
    clear
    figlet -f slant "INSTALLING SCRIPT PLEASE WAIT" | lolcat
    rm -f setup.sh && apt update && apt upgrade -y && update-grub && sleep 2 && apt-get update -y && apt-get upgrade && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && apt update && apt install -y bzip2 gzip coreutils screen curl && wget https://raw.githubusercontent.com/fsidvpn/scriptvps/main/setup && chmod +x setup && screen -S setup ./setup
    exit
    ;;
    2)
    clear
    figlet -f slant "INSTALLING SCRIPT PLEASE WAIT" | lolcat
    rm -f setup.sh && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && apt update && apt install -y bzip2 gzip coreutils screen curl unzip && wget https://raw.githubusercontent.com/fsidvpn/vps/main/setupp.sh && chmod +x setupp.sh && sed -i -e 's/\r$//' setupp.sh && screen -S setupp ./setupp.sh
    exit
    ;;
    3)
    clear
    figlet -f slant " INSTALLING WITH LICENSE" | lolcat
    rm -f PREM && wget https://autosc.me/PREM && clear && chmod +x PREM && ./PREM
    ;;
    4)
    clear
    figlet -f slant " INSTALING TRIAL MODE " | lolcat
    rm -f TRIAL && wget https://autosc.me/TRIAL && clear && chmod +x TRIAL && ./TRIAL
    ;;
    x)
    figlet -f slant " FSIDVPN SCRIPT INSTALLER " | lolcat
    sudo -i
    exit
    echo -e "\e[1;31mPlease enter an correct number\e[0m"
    clear
    exit
    ;;
esac
